# Generated by Django 3.2 on 2025-02-28 13:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'ordering': ('username',), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'Аутентифицированный пользователь'), ('moderator', 'Модератор'), ('admin', 'Администратор')], default='user', max_length=9, verbose_name='Роль'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Только буквы, цифры и @/./+/-/_', max_length=150, unique=True, validators=[django.core.validators.RegexValidator(message='Допустимы только буквы, цифры и @/./+/-/_', regex='^[\\w.@+-]+$')], verbose_name='Логин'),
        ),
    ]
