# Generated by Django 3.2 on 2025-02-25 12:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Максимум 150 символов. Только буквы, цифры и @/./+/-/_', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
