# Generated by Django 3.2 on 2025-02-26 07:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250225_1541'),
        ('users', '0002_auto_20250226_1308'),
    ]

    operations = [
    ]
