# Generated by Django 3.2 on 2025-02-28 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20250228_1605'),
        ('users', '0003_alter_user_confirmation_code'),
    ]

    operations = [
    ]
